import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import ProductCard from '../components/common/productCard';
import { Grid, Link } from '@mui/material';

export default function Home() {

  const fetcher = (url) => fetch(url).then((res) => res.json());
  const { data, error } = useSWR('http://localhost:1337/products', fetcher);

  console.log(error);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{flexGrow: 1}}>
        <Grid container spacing={2}>
          {(data && !error) &&
            data.map((product) =>
              <Grid item xs={12} sm={6} md={6} lg={6} xl={4} key={product.slug}>
                <Link href={`/product/${product.slug}`}>
                  <ProductCard product={product} />
                  </Link>
              </Grid>
            )
          }
        </Grid>
        </div>
      </main>
    </div>
  );
}
